version: '3.10'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "8101:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.config/environment/development/.env

  app:
    build:
      context: .
      dockerfile: compose/app/Dockerfile
    command: ./compose/app/scripts/init.sh
    volumes:
      - .:/code
    ports:
      - "8102:8102"
      - "8103:6655"
    restart: always
    depends_on:
      - db
    env_file:
      - ./.config/environment/development/.env

volumes:
  db_data: